### ISSUE TITLE
'Signature Dist' upload error

### ISSUE THREAD

**Issue by jtengjia** [Nobel-Justin/Oviz-Bio-demo#1]
Hello. First I want to say your visualization is wonderful. I encountered an error when I upload my data as specified format when I used  'Signature Dist' visualization section, even it didn't work uploading your own "Mut_Signature_dist_demo" file. Other visualization sections work well.
Please check~

**Comment by Nobel-Justin** [comment]
Dear jtengjia, thanks a lot. We have fixed this upload error.
