### ISSUE TITLE
How to get invitation code

### ISSUE THREAD

**Issue by pradyumnasagar** [Nobel-Justin/Oviz-Bio-demo#3]
I found the tool through Research article in NAR, it was said the tool is freely available but https://bio.oviz.org/users/sign_up says you need invitation code.
Can I please get an invitation code to register.
Thank you

**Comment by thelingxichen** [comment]
Hi, @pradyumnasagar the website requires no registration, please use this link https://bio.oviz.org/demo-project to run visualizations.
